# Continuous Deployment workflow
name: CD

# runs on push on the main branches
on:
  push:
    branches:
      - master
      - main
      - develop
      - fargate-discovery

# one job and step to deploy
jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ 1.8 ] # TODO configured in integrate.yml and deploy.yml
    # set the AWS token to access the S3 bucket for the maven repository
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    steps:
      # Checks-out the repository under $GITHUB_WORKSPACE, so the job can access it
      - uses: actions/checkout@v2

      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}

      - name: Cache Maven repository
        uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-java${{ matrix.java }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-java${{ matrix.java }}-maven-
            ${{ runner.os }}-

      # deploy
      - name: Maven deploy
        run: |
          mvn deploy
