# Continuous Integration workflow
name: CI

# run all integration jobs on pull request
on:
  pull_request

jobs:
  # one job for building and testing
  build_test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ 1.8 ]
    steps:
      # Checks-out the repository under $GITHUB_WORKSPACE, so the job can access it
      - uses: actions/checkout@v2

      # TODO check as first step if code formatting with .editorconfig is applied properly

      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}

      - name: Cache Maven repository
        uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-java${{ matrix.java }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-java${{ matrix.java }}-maven-
            ${{ runner.os }}-

      # compile
      - name: Maven build
        run: |
          mvn compile

      # test
      - name: Maven test
        run: |
          mvn test
